version: '3.8'

services:
  web:
    build:
      context: .
    command: >
      sh -c "
      python manage.py wait_for_db &&
      python manage.py migrate &&
      python manage.py loaddata category_data.json &&
      python manage.py loaddata product_data.json &&
      python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=django-insecure-u5us!^cz+r9it(t6nc=5z+huy@c*xz!435)1b_^3q-yjpk5lk$
      - DEBUG=True
      - DB_NAME=webstore
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_HOST=db
      - DB_PORT=5432
    depends_on:
      - db

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: webstore
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: